CODEX_FLOW_BASE_REF='origin/main'
CODEX_FLOW_BASE_BRANCH='main'
CODEX_FLOW_BRANCH_PREFIX='issue/'
CODEX_FLOW_CHECKS_COMMAND='./tools/checks/run_changed.sh'
CODEX_FLOW_PROMPTS_DIR='tools/codex/prompts'
CODEX_FLOW_PR_DRAFT_DEFAULT=1

CODEX_FLOW_WRITE_PROFILE='write'
CODEX_FLOW_READ_PROFILE='read'
CODEX_FLOW_PROFILE_WRITE_SANDBOX='danger-full-access'
CODEX_FLOW_PROFILE_WRITE_REASONING='xhigh'
CODEX_FLOW_PROFILE_READ_SANDBOX='danger-full-access'
CODEX_FLOW_PROFILE_READ_REASONING='medium'
