# shellcheck shell=bash
# shellcheck disable=SC2034

CODEX_FLOW_BASE_REF='origin/main'
CODEX_FLOW_BASE_BRANCH='main'
CODEX_FLOW_BRANCH_PREFIX='issue/'
CODEX_FLOW_CHECKS_COMMAND='./tools/checks/run_changed.sh'
CODEX_FLOW_PROMPTS_DIR='tools/codex/prompts'
CODEX_FLOW_PR_DRAFT_DEFAULT=1

CODEX_FLOW_PROFILE_WRITE_SANDBOX='danger-full-access'
CODEX_FLOW_PROFILE_WRITE_REASONING='xhigh'
CODEX_FLOW_PROFILE_READ_SANDBOX='danger-full-access'
CODEX_FLOW_PROFILE_READ_REASONING='medium'

CODEX_FLOW_IMPLEMENTATION_REASONING='high'
CODEX_FLOW_CHECK_FIX_REASONING='xhigh'
CODEX_FLOW_REVIEW_REASONING='medium'
CODEX_FLOW_REVIEW_FIX_REASONING='xhigh'
